### ISSUE TITLE
[BUG] Not able to compile

### ISSUE THREAD

**Issue by sashajov** [totles/z4lab-surftimer#101]
Hello, I am not able to compile your plugin on sm 1.10.

I tried to update smlib, but doesn't help.

//SourceMod Batch Compiler
// by the SourceMod Dev Team

//// SurfTimer.sp
//
// C:\Users\lesa\Desktop\sourcemod-1.10.0-git6458-windows\addons\sourcemod\scripting\include\smlib/entities.inc(1773) : fatal error 196: deprecated syntax; see https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Typedefs
//
// Compilation aborted.
// 1 Error.
//
// Compilation Time: 0.41 sec
// ----------------------------------------

Press enter to exit ...

Thanks in advance.

**Comment by 13ace37** [comment]
That's not our fault. Got the same errors while trying to compile on windows. There is a new version of smlib that fixed the problem for me.

**Comment by sashajov** [comment]
Can you send me please that smlib version? I tried all smlib versions.

**Comment by 13ace37** [comment]
[include.zip](https://github.com/totles/z4lab-surftimer/files/3906677/include.zip)

**Comment by sashajov** [comment]
//SourceMod Batch Compiler
// by the SourceMod Dev Team


//// SurfTimer.sp
//
// C:\Users\lesa\Desktop\110\sourcemod-1.10.0-git6458-windows (1)\addons\sourcemod\scripting\include\smlib/colors.inc(78) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// C:\Users\lesa\Desktop\110\sourcemod-1.10.0-git6458-windows (1)\addons\sourcemod\scripting\SurfTimer.sp(366) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// C:\Users\lesa\Desktop\110\sourcemod-1.10.0-git6458-windows (1)\addons\sourcemod\scripting\SurfTimer.sp(1382) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/misc.sp(2289) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/misc.sp(2397) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/misc.sp(2456) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/misc.sp(2487) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/sql.sp(1754) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/commands.sp(2053) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/replay.sp(881) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/replay.sp(898) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/replay.sp(913) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/trails.sp(398) : error 128: cannot return an array of indeterminate length
//
// 1 Error.
//
// Compilation Time: 1.97 sec
// ----------------------------------------

Press enter to exit ...

After smlib update. Do you have some idea to help me? :)

**Comment by 13ace37** [comment]
Then I can't help you there. Linux compiling works fine.

**Comment by sashajov** [comment]
Linux compiling works fine? Ohh I will try, thanks. On SM 1.10?

**Comment by sashajov** [comment]
I tried on Linux.

Sourcemod version 1.10 - build 6458

All combinations, with and without smlib update.

I tried master, dev and hotfix of your plugin, also I tried SurfTimer 280pre

and nothing...

What SM 1.10 build you are using?

**Comment by 13ace37** [comment]
I'm still compiling with SM 1.9 but it was working with 1.10 @ 6456 too.

**Comment by sashajov** [comment]
Okay, I will try with 6456, if not working I will continue with SM 1.9. ty
