### ISSUE TITLE
[BUG] On Styles Change Won't let me go thru check points.

### ISSUE THREAD

**Issue by uGamers** [totles/z4lab-surftimer#102]
**Describe the bug**

The issues is when I switch to a fun style and go thru the map it does not give me check point info which is ok but then at end of map will not let me complete saying I missed a check point. I have the check points filling the whole area and works fine in normal.

**Expected behavior**

Let me complete the map.

**Screenshots**

[https://imgur.com/a/iyzcX7d](url)

What you will see in this pic is I typed /Styles picked Fast fun style and went thru the map and at the end it says I can't pass map because I did not go thru all check points. I teleported back to start and did it again and now you can see that message did not come up and I was able to complete the map. Is something not unregistering when changing to fun styles?

**Additional context**

**Comment by 13ace37** [comment]
Either you disable it or you wont create the zone by hand.

I can't really help you anyway, since the infos you provided are only "frontend" i would like to see your zones table for this map.

**Comment by uGamers** [comment]
You said not create the zone by hand is there a command that auto does this?

**Comment by 13ace37** [comment]
`sm_hookzone`

**Comment by uGamers** [comment]
Still loss maybe im stupid but  when I do this command... say I wanted 3 check points do I have todo cp1 cp2 cp3 also do I have to do start and end same way with hookzone? Sorry ive been trying. When I do cp1 then cp2 save it and run the map the first cp I cross says it 2 and not 1 but I did 1 first. Hope you understand me :D

**Comment by uGamers** [comment]
Seems if I make one at a time then map change after each one works fine idk

**Comment by 13ace37** [comment]
1. Just delete all zones from the database
1. reload the map using `sm_rm`
1. create start and end zone using `sm_hookzone`
1. create cps using `sm_hookzone`
1. reload the map using `sm_rm`
1. create bonuses in the correct order using `sm_hookzone`

**Comment by 13ace37** [comment]
no answer after 2 days. reopen if needed!
