### ISSUE TITLE
[BUG] Missing trail materials

### ISSUE THREAD

**Issue by qawery-just-sad** [totles/z4lab-surftimer#109]
**Describe the bug**
The timer is missing materials from [Trails-Chroma](https://github.com/Nickelony/Trails-Chroma)

**Expected behavior**
Materials beeing included with timer?

**Screenshots**
![image](https://user-images.githubusercontent.com/53490397/73554141-771f5700-444b-11ea-806a-b7da64f8ffca.png)

**Additional context**
No.

**Comment by 13ace37** [comment]
fixed in https://github.com/z4lab/z4lab-surftimer/commit/dcd0c4ea2b5f9f50038c33dc7e3f1f3ef26c86b3
