### ISSUE TITLE
[Suggestion] cvar for the replay data location

### ISSUE THREAD

**Issue by TheGunter24** [totles/z4lab-surftimer#110]
**Is your feature request related to a problem? Please describe.**
currently when having multiple servers connected to the same db, the replays will be different since the data is stored locally on each server.

**Describe the solution you'd like**
a convar which allows to change the store location of replays. default: "/addons/sourcemod/data/replays" custom: "\csgo\serverfiles\replays"

**Describe alternatives you've considered**
nothing i would think of, instead of trying to modify the surftimer myself

**Additional context**
./.

**Comment by 13ace37** [comment]
> nothing i would think of, instead of trying to modify the surftimer myself

How about `ln -s`
