### ISSUE TITLE
How do I create stages ?

### ISSUE THREAD

**Issue by abhishekdeshkar** [totles/z4lab-surftimer#113]
Hi,

I know this is very basic question but I ended up wasting entire day and still couldn't figure it out.

So I tried to create stages using Zone creator. sm_zones command.

For first stage : I kept as ```Start - 0 and End - 0```
For second stage : I created ```Stage - 2 Zone``` . and ```Start 1 - End - 1```.

This is how you create stages ?

Please help me out.

**Comment by 13ace37** [comment]
just create a start zone at the start of the map and the end zone at the end of the map (not stage). after that, create stage zones at the start of all stages. a stage zone is the end zone for the stage before. so s2 is the end zone of s1...
