### ISSUE TITLE
[BUG] Replay, WRCP and Timeleft BOT issue

### ISSUE THREAD

**Issue by Cruze03** [totles/z4lab-surftimer#114]
**Describe the bug**
!fixbot doesn't fix this issue. Only 1 bot works.

**Expected behavior**
Shouldn't infinite loop on adding bot to server I guess?

**Screenshots**
![SS](https://user-images.githubusercontent.com/31343375/77827946-b2ce5880-713e-11ea-88e6-43e871e0d996.gif)

**Comment by 13ace37** [comment]
How about some infos??

**Comment by Cruze03** [comment]
Fresh installed server with SM and MM 1.10
Only **SurfTimer**, **discord_api** and **FixHintColorMessages** is the external plugin we're using in this server. No error logs and casual gamemode.

**Comment by 13ace37** [comment]
Remove FixHintColorMessages. SurfTimer Version?

**Comment by Cruze03** [comment]
Removed FixHintColorMessages, still the same.We're using 280pre right now but we faced this issue in 274 too. :(

**Comment by 13ace37** [comment]
You need to compile the dev branch your self. That's the most updated version.

**Comment by Cruze03** [comment]
My bad. That's some server issue because I'm facing the same without the plugin. Sorry to trouble and have a nice day!
