### ISSUE TITLE
[BUG] Speed cap at 2500 even when sv_maxvelocity is 4500

### ISSUE THREAD

**Issue by g2dgaming** [totles/z4lab-surftimer#115]
Hey , I am currently running Your surftimer plugin on my server , and some players are complaining that their speed is gettting capped at 2500  even when the maxvelocity is set at 4500.
I am not getting any error log and its all clear. But the players when they restart their game, it gets fixed.
THE PLUGINS I'm using:
[SM] Listing 49 plugins:
  01 "Thirdperson | Mirrow Mode" (1.11) by Zephyrus
  02 "Basic Info Triggers" (1.10.0.6453) by AlliedModders LLC
  03 "SourceBans++: SourceComms" (1.6.3) by Alex, SourceBans++ Dev Team
  04 "Weapons & Knives" (1.5.0) by kgns | oyunhost.net
  05 "Basic Commands" (1.10.0.6453) by AlliedModders LLC
  06 "Fun Commands" (1.10.0.6453) by AlliedModders LLC
  07 "SourceBans++: Admin Config Loader" (1.6.3) by AlliedModders LLC, SourceBans++ Dev Team
  08 "CallAdmin: Steam module" (0.1.8) by Impact, dordnung
  09 "Admin Help" (1.10.0.6453) by AlliedModders LLC
  10 "Player Commands" (1.10.0.6453) by AlliedModders LLC
  11 "Discord: CallAdmin" (1.1) by .#Zipcore
  12 "SM Franug Plugin list blocker" (1.6 (CSGO version)) by Franc1sco steam: franug
  13 "Anti-Flood" (1.10.0.6453) by AlliedModders LLC
  14 "Store - The Resurrection" (1.1) by Zephyrus
  15 "tVip - Reserved Slots" (2.3) by Plock, Totenfluch
  16 "MapChooser" (1.10.0.6453) by AlliedModders LLC
  17 "CallAdmin" (0.1.8) by Impact, dordnung
  18 "Discord: SourceBans" (1.0) by .#Zipcore
  19 "SM File/Folder Downloader and Precacher" (1.4) by SWAT_88
  20 "Chat-Processor" (2.1.2) by Keith Warren (Aerial Vanguard)
  21 "RandomCycle" (1.10.0.6453) by AlliedModders LLC
  22 "Client Preferences" (1.10.0.6453) by AlliedModders LLC
  23 "SM Fortnite Emotes Extended" (1.4.2) by Kodua, Franc1sco franug, TheBO$$
  24 "Admin Menu" (1.10.0.6453) by AlliedModders LLC
  25 "-N- Arms Fix" (2.0.2) by NomisCZ (-N-)
  26 "Basic Comm Control" (1.10.0.6453) by AlliedModders LLC
  27 "SourceBans++ Discord Plugin" (1.1.0) by RumbleFrog, SourceBans++ Dev Team
  28 "Basic Votes" (1.10.0.6453) by AlliedModders LLC
  29 "Nextmap" (1.10.0.6453) by AlliedModders LLC
  30 "Fun Votes" (1.10.0.6453) by AlliedModders LLC
  31 "SourceBans++ Report Plugin" (1.6.3) by RumbleFrog, SourceBans++ Dev Team
  32 "tVip" (69) by tVip Modified LOT/G2DGaming
  33 "Discord: SourceComms" (1.1) by .#Zipcore
  34 "SurfTimer" (274) by [z4lab] - Maintainer: Ace & totles
  35 "Rock The Vote" (1.10.0.6453) by AlliedModders LLC
  36 "Test Messages" (1.0.0) by Keith Warren (Shaders Allen)
  37 "Admin File Reader" (1.10.0.6453) by AlliedModders LLC
  38 "Reserved Slots" (1.10.0.6460) by AlliedModders LLC
  39 "SourceBans++: Bans Checker" (1.6.3) by psychonic, Ca$h Munny, SourceBans++ Dev Team
  40 "PlayerSkin" (5.0.1 (Build 4)) by noBrain
  41 "Store - Trade System" (1.0) by Zephyrus
  42 "Map Nominations" (1.10.0.6453) by AlliedModders LLC
  43 "Vote Mute/Vote Silence" (1.0.105) by <eVa>Dog/AlliedModders LLC
  44 "Sound Commands" (1.10.0.6453) by AlliedModders LLC
  45 "Fix Hint Color Messages" (1.1) by Phoenix (˙·٠●Феникс●٠·˙) and Franc1sco Franug
  46 "Discord API" (1.0) by .#Zipcore, Credits: Shavit, bara, ImACow and Phire
  47 "SourceBans++: Main Plugin" (1.6.3) by SourceBans Development Team, SourceBans++ Dev Team
  48 "Discord API" (0.1.97) by Deathknife
  49 "Basic Chat" (1.10.0.6453) by AlliedModders LLC

Please help!

**Comment by 13ace37** [comment]
Not following the issue rules.

**Comment by g2dgaming** [comment]
i'm very new to this bro, please help me!
