### ISSUE TITLE
[BUG] Speed Cap at 2500 for random players!

### ISSUE THREAD

**Issue by g2dgaming** [totles/z4lab-surftimer#116]
SURFTIMER VERSION: 280PRE (Tried last 3 versions, still facing same issue)
Sourcemod version: 1.10 - build 6480
Metamod version:  1.10 - build 971
Random people irrespective of their flags are getting their speed capped at 2500. even when the sv_maxvelocity is 4500 . If I reboot the server or change map, it gets fixed.There are no error logs regarding it.And also, I'm using the original version and haven't modded anything in your plugin.

**Comment by 13ace37** [comment]
Not following the issue rules. Warning 2.

**Comment by g2dgaming** [comment]
> Not following the issue rules. Warning 2.

Bro as I told you, I'm new, Please tell me whats wrong

**Comment by 13ace37** [comment]
Is it that hard to read?

**Comment by g2dgaming** [comment]
what was wrong, I posted everything bro, i need your help, ignore me for being noob

**Comment by 13ace37** [comment]
I really do feel answering this BUT. 
> what was wrong, I posted everything bro
1. > You're following the template - That means you won't delete any pre-entered questions!
2. You got several plugins who provide the exact same functions the timer already has. So that means either they or the timer will run into problems. 
3. Also, the timer won't crash/run into unexpected situations without an error log.

**Comment by g2dgaming** [comment]
Which plugin is that, please tell me bro

**Comment by 13ace37** [comment]
> 45 "Fix Hint Color Messages" (1.1) by Phoenix (˙·٠●Феникс●٠·˙) and Franc1sco Franug

can't see the other anymore

**Comment by g2dgaming** [comment]
This has been since the beginning, never got speed cap! Any other you think?

**Comment by 13ace37** [comment]
Still.... remove it the timer does the same thing. This will 100% cause server crashes at some point.

**Comment by g2dgaming** [comment]
ok I removed it, but i think this won't fix my speed cap issue

**Comment by g2dgaming** [comment]
Bro as I said, i removed it, still the speed is getting capped
