### ISSUE TITLE
[BUG] Bonus prestrafe showing Stage prestrafe

### ISSUE THREAD

**Issue by 13ace37** [totles/z4lab-surftimer#119]
**Describe the bug**
When you finish a stage or switch from a stage to a bonus the stage prestrafe keeps showing.

**Screenshots**
![image](https://user-images.githubusercontent.com/29045525/78384660-e0058580-75da-11ea-998f-7667e360ade6.png)

**Comment by olokos** [comment]
Have you managed to solve this issue? Not sure why it's closed now 🤔

**Comment by 13ace37** [comment]
> Any currently open or new requests/issues will be closed/ignored!

**Comment by olokos** [comment]
Can you let them stay for now?
I will move the open issues to the other repo, this will make it harder for me.
I can't really see where you wrote that current or new issues will be removed, but okay.
Oh, I see it's too late now, sadly. That is fine too.
