### ISSUE TITLE
[Suggestion]Add support for Up to Tier 8 maps.

### ISSUE THREAD

**Issue by EuanMosit** [totles/z4lab-surftimer#123]
**Is your feature request related to a problem? Please describe.**
Many communities are setting some maps to tier 7 & 8. We are currently limited to 6.

**Describe the solution you'd like**
Increase limit from tier 6 to tier 8

**Describe alternatives you've considered**
Could just not up the tiers, but would start getting bigger consistency issues betweeen servers

**Additional context**
This is not a hard thing to implement, and would probably only take 30 mins to do, but would be appreciated by a lot of top level surfers and communitites

**Comment by 13ace37** [comment]
There are no t7 or t8 maps??

**Comment by EuanMosit** [comment]
KSF announced they are changing
pls -> t7
sinsane2 -> t7
raphaello -> t7
goliath -> t7
devil -> t7
corruption -> t8
not_so_zen -> t7

While some of these are cs:s maps, there are cs:go maps. Many other communities follow KSFs guidelines for map tiers, and there may be new maps that start out as tier 7 or 8

**Comment by 13ace37** [comment]
> KSF announced they are changing

Do you still think KSF is "the" surf community out there? For Source maybe but 100% not for GO. 

Also in the surf community, you might say "oh yeah that's a t7 map". But in reality, there is no tier 7 or even 8!
That's why I won't allow tiers higher than 6.

**Comment by EuanMosit** [comment]
While not everyone will agree with t7 and t8 maps, there are quite a few that will. It doesn't affect those who don't want to change it, but will help those who do want it. 
Given the ease with which the change could be made I don't see why it couldn't just be added to help those communtites.
