### ISSUE TITLE
[BUG] Error Creating Table.

### ISSUE THREAD

**Issue by musoviich** [totles/z4lab-surftimer#128]
**Describe the bug**
Plugin is working, but it cant connect on mysql server.

**Expected behavior**
L 04/08/2020 - 13:04:12: [SM] Exception reported: [Surftimer] Database tables could not be created! Error: Lost connection to MySQL server during query

L 04/08/2020 - 13:04:12: [SM] Blaming: surftimer.smx

L 04/08/2020 - 13:04:12: [SM] Call stack trace:

L 04/08/2020 - 13:04:12: [SM]   [0] SetFailState

L 04/08/2020 - 13:04:12: [SM]   [1] Line 118, surftimer/sql.sp::SQLTxn_CreateDatabaseFailed

**Comment by olokos** [comment]
We need more information than that.
What OS are you running?
What DB engine are you using?
The plugin is confirmed working with MySQL5.7, MySQL8+ and MariaDB.
Did you make sure your databases.cfg is setup correctly?

**Comment by musoviich** [comment]
Server OS: Ubuntu 18.04
MySQL Server: 10.0.38-MariaDB-cll-lve - MariaDB Server 

DB Engine: MySQL

Database.cfg settings are:

`"Databases"
{
	"driver_default"		"mysql"
	
	// When specifying "host", you may use an IP address, a hostname, or a socket file path
	
	"default"
	{
		"driver"			"default"
		"host"				"localhost"
		"database"			"sourcemod"
		"user"				"root"
		"pass"				""
		//"timeout"			"0"
		//"port"			"0"
	}
	
	"storage-local"
	{
		"driver"			"sqlite"
		"database"			"sourcemod-local"
	}

	"clientprefs"
	{
		"driver"			"sqlite"
		"host"				"localhost"
		"database"			"clientprefs-sqlite"
		"user"				"root"
		"pass"				""
		//"timeout"			"0"
		//"port"			"0"
	}

	"sourcebans"
	{
		"driver"			"mysql"
		"host"				"185.61.137.171"
		"database"			"deepfear_banovi"
		"user"				"deepfear_webot"
		"pass"				"**"
		//"timeout"			"0"
		"port"			"3306"
	}

	"surftimer"
	{
		"driver"			"mysql"
		"host"				"185.61.137.171"
		"database"			"deepfear_rankmeSurf"
		"user"				"deepfear_webotSurf"
		"pass"				"**"
		//"timeout"			"0"
		"port"			"3306"
	}
}
`

**Comment by musoviich** [comment]
Could PHP7 Version be the problem ?

**Comment by olokos** [comment]
do you have your DB on a different server than csgo?
That's the only instance where you would put ip in host section instead of localhost.
PHP7 has nothing to do with it, I'm running 7.4.
In some dbs you're using sqlite and localhost and in others mysql and ip address, just use one db engine.

Do not use root as user, to any of the databases, especially when the password is saved in databases.cfg

If you're running the db server on the same machine as csgo
then you need to replace 185.61.137.171 with localhost.

**Comment by musoviich** [comment]
MySQL Server is on my webhost.
CSGO Server is on my dedicated machine.
- So 2 different IP's, Locations, etc...

storage-local, client-prefs generated by default sourcemod. can i remove them ?

Im using only mysql

**Comment by olokos** [comment]
On a second look it seems to be unrelated to storage-local and client-prefs.
I have both connected to MySQL database, but you can try commenting them out of databases.cfg and checking out what happens in server console.

In this situation I would recommend you check you can actually connect to your MySQL server manually, while you're on the csgo server.

``mysql -u deepfear_rankmeSurf -h 185.61.137.171 -p``

Maybe your port 3306 is closed?

**Comment by musoviich** [comment]
Its not closed, becouse I'm using sourcebans and its working fine...

`root@localhost:~# mysql -u deepfear_webotSurf -h 185.61.137.171 -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 1617637
Server version: 10.0.38-MariaDB-cll-lve MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>
`

I tried and its working...

Edit: Tried from CSGO Server Machine

**Comment by 13ace37** [comment]
```
L 04/08/2020 - 13:04:12: [SM] Exception reported: [Surftimer] Database tables could not be created! Error: Lost connection to MySQL server during query

L 04/08/2020 - 13:04:12: [SM] Blaming: surftimer.smx

L 04/08/2020 - 13:04:12: [SM] Call stack trace:

L 04/08/2020 - 13:04:12: [SM] [0] SetFailState

L 04/08/2020 - 13:04:12: [SM] [1] Line 118, surftimer/sql.sp::SQLTxn_CreateDatabaseFailed
```


This happens since SM1.10 while using long queries. There will be a "fix"/workaround soon.
Try to create all table by hand for now.

**Comment by musoviich** [comment]
Sorry bro problem was with my web hosting operator, they have problem with databases

i tried with another webspace (nitrado) and everything is working well.
