### ISSUE TITLE
[BUG] ck_playerrank cleared on server shutdown

### ISSUE THREAD

**Issue by jfoerste** [totles/z4lab-surftimer#129]
**Describe the bug**
The ck_playerrank table is reset upon shutting down the server. Therefore all player ranks are reset when restarting the server.

**Expected behavior**
The ck_playerrank table should not be cleared upon server shutdown.

**Screenshots**

**Plugin List**
 "Admin File Reader" (1.10.0.6478) by AlliedModders LLC
 "Basic Chat" (1.10.0.6478) by AlliedModders LLC
 "Reserved Slots" (1.10.0.6478) by AlliedModders LLC
 "SurfTimer" (281) by Ace & olokos
 "Basic Comm Control" (1.10.0.6478) by AlliedModders LLC
 "Fun Votes" (1.10.0.6478) by AlliedModders LLC
 "Fun Commands" (1.10.0.6478) by AlliedModders LLC
 "Sound Commands" (1.10.0.6478) by AlliedModders LLC
 "Basic Votes" (1.10.0.6478) by AlliedModders LLC
 "Admin Menu" (1.10.0.6478) by AlliedModders LLC
 "Basic Info Triggers" (1.10.0.6478) by AlliedModders LLC
 "Rock The Vote" (1.10.0.6478) by AlliedModders LLC
 "Map Nominations" (1.10.0.6478) by AlliedModders LLC
 "Anti-Flood" (1.10.0.6478) by AlliedModders LLC
 "Discord API" (0.1.97) by Deathknife
 "Admin Help" (1.10.0.6478) by AlliedModders LLC
 "Player Commands" (1.10.0.6478) by AlliedModders LLC
 "Basic Commands" (1.10.0.6478) by AlliedModders LLC
 "Client Preferences" (1.10.0.6478) by AlliedModders LLC
 "Basic Ban Commands" (1.10.0.6478) by AlliedModders LLC
 "MapChooser" (1.10.0.6478) by AlliedModders LLC
 "Nextmap" (1.10.0.6478) by AlliedModders LLC

**Additional context**

**Comment by 13ace37** [comment]
Are your maps ranked?

**Comment by jfoerste** [comment]
Not that I'm aware of.

**Comment by jfoerste** [comment]
This happens as well upon goin into hibernation.

**Comment by 13ace37** [comment]
You need to set maptier.
