### ISSUE TITLE
[Suggestion] more config options

### ISSUE THREAD

**Issue by TheGunter24** [totles/z4lab-surftimer#23]
options to enable / disable the following feature:
- surf modes like "low gravity" "fast forward" etc
- specifiq settings within !timer (like forceing the chat to always be displayed)

more options in:
- a convar to specify the discord bot name +(maybe a config to define the discord messages)
- recalc of playerranks, maybe make a 2.nd command which will recalc the complete database
- 2 options in default_titles to enable / disable the country tag in chat or / and scoreboard
- a option to set the time for playersettings to be deleted (this would need a "last seen" in db, would reduce the mess in db :D)

**Comment by 13ace37** [comment]
> a convar to specify the discord bot name +(maybe a config to define the discord messages)

can be changed through the discord webhook

> recalc of playerranks, maybe make a 2.nd command which will recalc the complete database

the command is already recalculation the "whole" player database

> a option to set the time for playersettings to be deleted (this would need a "last seen" in db, would reduce the mess in db :D)

I don't get it

> specifiq settings within !timer (like forceing the chat to always be displayed)

there you should ask valve not sm

**Comment by TheGunter24** [comment]
> > a convar to specify the discord bot name +(maybe a config to define the discord messages)
> 
> can be changed through the discord webhook
> 
not sure how, the webhook name is different then the bot name from the send message.

> > a option to set the time for playersettings to be deleted (this would need a "last seen" in db, would reduce the mess in db :D)
> 
> I don't get it
> 
just to clean up the database from users that where one time players, to reduce the amount of stored data.
so lets say when a player is not online for 14 days his playersettings will be deleted from the db
