### ISSUE TITLE
[Bug] ck_colored_chatnames will override the name color of default_titles

### ISSUE THREAD

**Issue by TheGunter24** [totles/z4lab-surftimer#24]
when having "ck_colored_chatnames 1" the style / color options in default_titles will be overwritten

my default_titles https://pastebin.com/CcDni6ry

my skillgroups https://pastebin.com/tZP35Yiq

**Comment by 13ace37** [comment]
I don't really understand your problem 🤔.

**Comment by 13ace37** [comment]
You should answer and don't just edit your message ^^

But im see your problem and im looking into it.

**Comment by 13ace37** [comment]
https://github.com/totles/z4lab-surftimer/commit/4381c12b61fba33ed678f61f648d5f870c1e79b3
