### ISSUE TITLE
[Suggestion] improve the !dr

### ISSUE THREAD

**Issue by TheGunter24** [totles/z4lab-surftimer#27]
maybe a option in the ingame menu to "mark" multiple times, then delete all these at once
or / and 
the menu will open again after delete
a option in config to disable the "delete security"

**Comment by 13ace37** [comment]
I'll stick to the last two ones. The first one can't be realized in a good way. Try to stick to the database to remove multiple records.

**Comment by 13ace37** [comment]
https://github.com/totles/z4lab-surftimer/commit/83c01b34f124a4199fae3e730476374a94d14943
https://github.com/totles/z4lab-surftimer/commit/ae632a2c43d8ee9fbb9f81590cca44bc15c409d0
