### ISSUE TITLE
[?][Bug] playerrank is "exception" sometimes

### ISSUE THREAD

**Issue by TheGunter24** [totles/z4lab-surftimer#28]
it seems to occour randomly
here a example:
https://abload.de/img/20190624181859_1rnksg.jpg // https://docdro.id/ILpCnxe

i would say that like 0.8% or so is effected by this

no errors to be found in any log, everything normal

**Comment by 13ace37** [comment]
It isn't really a problem that comes from our timer. That's the maximum length for the player's clan tag. Just try to use shorter rank names.

**Comment by totles** [comment]
thank panorama UI for that :)
