### ISSUE TITLE
fluffy to your timer, but i get a error

### ISSUE THREAD

**Issue by freakexeuLow** [totles/z4lab-surftimer#29]
> L 07/29/2019 - 21:54:48: SourceMod error session started
L 07/29/2019 - 21:54:48: Info (map "surf_acp_fix") (file "/home/user2-25/server/csgo/csgo/addons/sourcemod/logs/errors_20190729.log")
L 07/29/2019 - 21:54:48: [surftimer.smx] [Surftimer] SQL Error (db_viewPlayerOptionsCallback): Unknown column 'prestrafe' in 'field list'

**Comment by 13ace37** [comment]
`USE surftimer
ALTER TABLE `ck_playeroptions2` 
ADD COLUMN `prestrafe` INT(11) NOT NULL DEFAULT '0' AFTER `module5s`;`

**Comment by 13ace37** [comment]
`USE surftimerpro
ALTER TABLE "ck_playeroptions2" 
ADD COLUMN "prestrafe" INT(11) NOT NULL DEFAULT '0' AFTER "module5s";`

**Comment by 13ace37** [comment]
https://pastebin.com/gSBaHZfh

**Comment by 13ace37** [comment]
https://github.com/totles/z4lab-surftimer/issues/18
