### ISSUE TITLE
Bhop

### ISSUE THREAD

**Issue by skradR** [totles/z4lab-surftimer#34]
Any idea if you can adapt this for bhop, such a nice plugin... just want to use it for the hops man ;)

Example 1) Booster resetting the style values.

https://youtu.be/KnNufm-pXcI

Example 2) Ladder resetting the style values.

https://youtu.be/VGkZNu35JFk

Example 3) Most boosters on maps doesn't affect the style values.

https://youtu.be/SEDeF6oJIG8

For some reason the different styles revert the user style back to normal when the player hits a boost or a ladder etc... 

Just curious if you know a way to prevent this or adapt the plugin for bhop. No hassle if not, just curious ;)

PS: Apologies for the video quality

**Comment by 13ace37** [comment]
I'ts called SurfTimer

**Comment by 13ace37** [comment]
https://bitbucket.org/kztimerglobalteam/gokz/src/master/
