### ISSUE TITLE
Add SteamWorks and SMJansson to release

### ISSUE THREAD

**Issue by totles** [totles/z4lab-surftimer#43]
license of both of them allow this

- https://forums.alliedmods.net/showthread.php?t=229556
- https://forums.alliedmods.net/showthread.php?t=184604

**Comment by StAwN74** [comment]
Speaking of licenses, can I ask you the discord_api.sp? We only have the .smx. Thank you.
And thank you for maintaining this.

**Comment by 13ace37** [comment]
I can't see a license 🤔 
https://github.com/Deathknife/sourcemod-discord/blob/master/discord_api.sp

**Comment by totles** [comment]
@StAwN74 is there a need for you to compile the discor_api.smx for yourself? Just asking since we don't find any licensing information from that and we don't have any changes in it anyway

**Comment by totles** [comment]
done https://github.com/totles/z4lab-surftimer/commit/05f7f89256578c98ae8056e1506ad63c4cc415d2

**Comment by StAwN74** [comment]
@totles exactly, I've been testing a lot of ckSurf and SurfTimer forks recently, and I've made my choice now. I am trying to compile my own version and the only thing I miss is that. Thx

**Comment by StAwN74** [comment]
@13ace37 This is the discord-api script I was looking for, right? Thx!

**Comment by 13ace37** [comment]
yes
