### ISSUE TITLE
[bug] loading surf_meme will referr to loading surf_me

### ISSUE THREAD

**Issue by TheGunter24** [totles/z4lab-surftimer#50]
https://steamcommunity.com/sharedfiles/filedetails/?id=669898648
meme

https://steamcommunity.com/sharedfiles/filedetails/?id=1193971616
me

thx

**Comment by 13ace37** [comment]
what do you mean?

**Comment by TheGunter24** [comment]
it loads surf_me when i try to load surf_meme

**Comment by 13ace37** [comment]
has nothing to do with the timer

**Comment by 13ace37** [comment]
https://github.com/totles/z4lab-mapchooser/commits/master
