### ISSUE TITLE
Centre + Side Hud

### ISSUE THREAD

**Issue by stunslave** [totles/z4lab-surftimer#51]
On server restart the centre and side hud is always set to "OFF" by default, anyway to change the HUDs to be set to "ON" by default. 

On map change the centre and side hud stays "ON". But server restart sets the centre and side HUD to "OFF" by default.

Don't want to reset the hud everytime the server crashes or is restarted.

EDIT: FIXED

**Comment by 13ace37** [comment]
happens if you havent updated your ck_playeroptions2 table
