### ISSUE TITLE
something wrong with prestrafe?

### ISSUE THREAD

**Issue by qawery-just-sad** [totles/z4lab-surftimer#56]
I'm running newest version of your timer 261 and i get this error everytime someone starts their run also speed is caped at 350units

L 08/09/2019 - 14:01:38: [SM] Exception reported: Language phrase "StartPrestrafe" not found (arg 5)
L 08/09/2019 - 14:01:38: [SM] Blaming: SurfTimer.smx
L 08/09/2019 - 14:01:38: [SM] Call stack trace:
L 08/09/2019 - 14:01:38: [SM]   [0] Format
L 08/09/2019 - 14:01:38: [SM]   [1] Line 93, surftimer/buttonpress.sp::CL_OnStartTimerPress
L 08/09/2019 - 14:01:38: [SM]   [2] Line 532, surftimer/surfzones.sp::EndTouch
L 08/09/2019 - 14:01:38: [SM]   [3] Line 297, surftimer/surfzones.sp::EndTouchTrigger

**Comment by 13ace37** [comment]
update your Translation File

**Comment by qawery-just-sad** [comment]
thank you
