### ISSUE TITLE
[Suggestion] Improve Prestige Rank & Server Record Announcements.

### ISSUE THREAD

**Issue by stunslave** [totles/z4lab-surftimer#58]
**Prestige Rank:**

Maybe create a Prestige Rank convar for VIP members only. (To have a server just for **VIP** Members)
Improve Prestige Rank for ranked styles only, not fun styles or add a convar for ranked styles only.

**Record/Cross server/Discord Announcements:**

and if possible create ranked style (HSW / BW / SW) announcements.

**Comment by 13ace37** [comment]
I don't really get what you mean by "Prestige Rank".

**Comment by stunslave** [comment]
// Prestige Server
	g_hPrestigeRank = CreateConVar("ck_prestige_rank", "0", "Rank of players who can join the server, 0 to disable");
	g_hPrestigeStyles = CreateConVar("ck_prestige_all_styles", "1", "If enabled, players must be the rank of ck_prestige_rank in ANY style");

ck_prestige_rank make one for VIP members. (ck_prestige_rank_vip) Which only allows VIP Members to connect to the server, instead of rank based server connect.
ck_prestige_all_styles and change or make a new one ck_prestige_ranked_styles

This would be awesome :>

**Comment by 13ace37** [comment]
There is already a ConVar like this. Or am I wrong?

**Comment by stunslave** [comment]
These are the convars (part of the timer currently). 

// Prestige Server
g_hPrestigeRank = CreateConVar("ck_prestige_rank", "0", "Rank of players who can join the server, 0 to disable");
g_hPrestigeStyles = CreateConVar("ck_prestige_all_styles", "1", "If enabled, players must be the rank of ck_prestige_rank in ANY style");

-------

ck_prestige_all_styles is for all styles, not for ranked styles only.
Ranked styles = Normal / HSW / BW / SW
Fun styles = Low-Gravity / Fast forward / Slow Motion

ck_prestige_rank is for rank based server connect (top 50 / Top 500 etc), not **(VIP ONLY)** player server connect.

**Comment by 13ace37** [comment]
Ah, now I get it! :D I'll take a look at it.

**Comment by 13ace37** [comment]
The VIP support wasn't really a problem but I'm having problems with making it ranked styles only ._.
