### ISSUE TITLE
sm_customtitle and colors

### ISSUE THREAD

**Issue by qawery-just-sad** [totles/z4lab-surftimer#59]
when trying to set custom title with color argument something strange occurs
Before comand
![bug](https://user-images.githubusercontent.com/53490397/62835855-3e9d7e00-bc5d-11e9-8b9a-ed3b507d9973.png)

After comand
![bug3](https://user-images.githubusercontent.com/53490397/62835864-51b04e00-bc5d-11e9-9eaa-af10f43af4cf.png)
![bug2](https://user-images.githubusercontent.com/53490397/62835878-79071b00-bc5d-11e9-803b-4d21eb4517e1.png)

**Comment by 13ace37** [comment]
1. Custom Titles aren't really supported anymore.
2. You should never set your title trough the chat.
3. Some informations about your colorvariables would be nice.

**Comment by 13ace37** [comment]
4. It works fine for me.
![image](https://user-images.githubusercontent.com/29045525/62836107-2bd87880-bc60-11e9-8fd9-6671b2978c3f.png)

**Comment by qawery-just-sad** [comment]
Found problem i didn't use quotation marks.
So solutions to the problem
1. Use quotation marks
2. Never use this command again
3. Delete the command
4. Make it dumb people proof

**Comment by stunslave** [comment]
I saw the topic closed but this will help anyone else that comes along looking for help.

Best way to edit your title is through console.

**sm_customtitle "{default}[{green}MY {darkblue}NEW {lime}TITLE{default}]"**

https://imgur.com/a/AjxkaFK
