### ISSUE TITLE
[BUG] sm_mapsettings max velocity

### ISSUE THREAD

**Issue by stunslave** [totles/z4lab-surftimer#61]
This is the latest 270 surftimer release.

Max velocity not saving after map change. 

It changes in db, but does not change in-game. 

Just using 3500 - 4000 as a example, any speed does not work.

When playing a map if I change the Max velocity from 3500 to 4000 it will change in-game for the period of time I'm playing the map, but after I restart the server / reload the map or come back to the map at a later stage, the Max velocity will change back to what it previously was 3500, this also effects the speed, sets it to 3500. 
Every time the map reloads the Max velocity needs to be changed again.

The Max velocity is not saving after restarting the server / reloading the map.
The DB Max velocity does change but does not revert back to 3500. But in-game the Max velocity reverts back to 3500 and in-game it doesn't use the Max velocity saved in the db. (This is hard to explain) 

**Screenshots**

Image to show that it is changing, but not saving after map reload.
https://imgur.com/a/bYgacgz

**Comment by 13ace37** [comment]
does it work when you use `sm_mv 4000` 🤔

**Comment by stunslave** [comment]
sm_mv 4000 does work but doesnt save after map reload or change, Max velocity reverts back to 3500. 

The db doesnt revert back. Stays on what ever I change it to. But doesnt effect the in-game speed.

**Comment by stunslave** [comment]
**Posting here instead of creating a new bug report.**

The max vel (sm_mapsettings) is still not saving, maybe check again. Tested on a couple of maps. Seems to be doing the same thing.

Changing the max vel while playing the map works (the speed changes) , but reloading the map or coming back to the map at a later stage the max vel will be back to default in map settings. (3500)
The db settings doesn't effect the speed in-game what so ever after the map reloads.
