### ISSUE TITLE
[BUG] Vip Feature Spam

### ISSUE THREAD

**Issue by stunslave** [totles/z4lab-surftimer#65]
Non VIP Players are getting spammed.
**"This is a VIP Feature"**

Might have something to do with the trails that were added.
Didn't happen in the version b4 270. (Happens in 270 and 271)

**Screenshots**
https://i.imgur.com/Pupjr16.jpg

**Comment by 13ace37** [comment]
not following the templates.

**Comment by totles** [comment]
@stunslave should be fixed with this commit: https://github.com/totles/z4lab-surftimer/commit/114ce1a005703678d3f7eff4f4c029ebc5925ca8 - there is no release for it yet tho so you need to compile yourself
