### ISSUE TITLE
[BUG] VIP Feature Spam - Version 272

### ISSUE THREAD

**Issue by stunslave** [totles/z4lab-surftimer#68]
Just a heads up.
The spam of "**This is a VIP Feature**" still happens in **version 272**.

This https://github.com/totles/z4lab-surftimer/commit/114ce1a005703678d3f7eff4f4c029ebc5925ca8 **Fixes the issue**.

I reverted back to this.

**Comment by 13ace37** [comment]
272 has this fix.

**Comment by stunslave** [comment]
I download the this " https://github.com/totles/z4lab-surftimer " / " https://github.com/totles/z4lab-surftimer/archive/master.zip " and https://github.com/totles/z4lab-surftimer/blob/master/addons/sourcemod/scripting/surftimer/misc.sp

Is set to >>> The old version. (I prefer to conpile the .sp manually.) :P

```
bool IsPlayerVip(int client, bool admin = true, bool reply = true)
{
	if (admin)
	{
		if (CheckCommandAccess(client, "", ADMFLAG_ROOT))
			return true;
	}

	if (!g_bVip[client] && !CheckCommandAccess(client, "", ADMFLAG_RESERVATION))
	{
		if (reply)
		{
			CPrintToChat(client, "%t", "Misc43", g_szChatPrefix);
			PrintToConsole(client, "surftimer | This is a VIP feature");
		}
		return false;
	}

	return true;
}
```

**Comment by 13ace37** [comment]
i dont really get what youre talking about. the fix is included in the master and the release

**Comment by stunslave** [comment]
What I mean is if u go to **Branch: master** and go to " z4lab-surftimer/addons/sourcemod/scripting/surftimer/misc.sp " The fix is not there.

If you download from the master branch the fix is not in the misc.sp

As shown in this image:
https://i.imgur.com/xWEHFtN.png

This is my last response I cant explain it any better than this. lol

I found it.
You revert it back by mistake - Revert "Merge branch 'dev'"

**Comment by totles** [comment]
Hi, I think I know what happend, we merged the dev branch in the master yesterday by accident and so lost some changes, thanks for the info, it should now be in the master: https://github.com/totles/z4lab-surftimer/commit/31fd807c58e3c1de8cc5b83226ac4f225c6d7c3d
