### ISSUE TITLE
[Suggestion] Teleport to Stage Zone + Replay Backups

### ISSUE THREAD

**Issue by stunslave** [totles/z4lab-surftimer#69]
**Teleport to Stage Zone:**
A zone to Teleport players to the start of a stage.
Basically the same as TeleToStart, but instead sends players to the beginning of the stage they are currently on.

TeleToStart works perfect for linear maps but isn't great for stage maps.

After placing the zone you can select what stage the **Teleport to Stage Zone** teleports the players to. (This can be used to block area's off as well as other things)

Screenshots:
https://i.imgur.com/DvVfdZu.png

--------------------------

**Replay Backup files:**
I noticed that the replays are backed-up quite far back. It would be great if they were backed-up when the record is broken or every 3rd or 4th time the record is beaten. 

So the backup replay files are from a much closer point to the current record replay/bugged replay. 

--------------------------

++
**Bug:** 
sm_mapsettings max velocity is still broken, u might wana test it again, seems to have the same problem as previously in https://github.com/totles/z4lab-surftimer/issues/61

**Comment by 13ace37** [comment]
1. Suggestion: I've never used a single TeleToStart zone in my whole 2 years of zoning.
1. The last 2 records will be saved. So I don't really understand what you're talking about.
1. I've tested this on like 3 maps back then. It's possible that there is the same problem that we had with the vip spam.

**Comment by stunslave** [comment]
Holy crap I use teletostart zones all the time. Almost every 2nd or 3rd map and I've been zoning for over 5 years. It is by far the most useful zone out of all the zones. Especially to quick fix something when I don't feel like using stripper to fix it.

The records. Don't ever backup (THE DATES), So I don't know what you mean lol.
https://i.imgur.com/sH6VF26.png

The max velocity has the fix in the newest version, I did check this earlier. It's still not working tho.

**Comment by 13ace37** [comment]
1. I won't add this cuz I don't see the reason. Use stripper configs for such things.
1. The `.bak` files are the backups
1. I see. I'll take a look at it again.

**Comment by 13ace37** [comment]
And could you please make separate issues for every single suggestion in the future. Thanks.

**Comment by 13ace37** [comment]
And I've also checked the "maxvel bug".

The maxvelocity will be applied if a player joins the server.

**Comment by totles** [comment]
I kinda start to feel a little tention between you guys, everything ok? :D @stunslave the .bak files are as @13ace37 said the backup, when a new record is done the old one record will overwrite the .bak file, so you always have the latest record + the record before that in your folder, if you wanna backup them regualry even more you can do this on your linux/windows server or simply with `rsync`

**Comment by stunslave** [comment]
Ye i know that, the point of the screenshot was to show the date of the backups. 2017, they are extremely old. So my point being is they don't backup, in which they should. 

The max vel bug I've tested on various maps, by restarting the server, changing the maps, and reloading the maps. So far the bug is still there. I tested on aircontrol earlier our surf_aircontrol was set to 10000, I changed it to 5000 in mapsettings. Changed the map and went back to surf_aircontrol the max vel was set to 3500 in mapsettings. In the db it was set to 5000. I surfed the map I couldn't gain more than 3500 speed on the map even though the db was set to 5000. (I cant explain this any better) But it is broken. 

Anyways you guys have a awesome surftimer, thanks for the quick responses!

**Comment by 13ace37** [comment]
> Ye i know that, the point of the screenshot was to show the date of the backups. 2017, they are extremely old. So my point being is they don't backup, in which they should.

This might be a permission issue.

Restarted the server and switched to the map:
![image](https://user-images.githubusercontent.com/29045525/63182960-18f4e800-c054-11e9-8f50-775073bdc8ff.png)
Joined the server:
![image](https://user-images.githubusercontent.com/29045525/63183000-3fb31e80-c054-11e9-87f3-f0ae23e5e6f8.png)

**Comment by totles** [comment]
@stunslave as @13ace37 said the backup thing sounds like a permission issue, try updating them

**Comment by stunslave** [comment]
Max Vel:

Screen:
https://i.imgur.com/BBkgiTw.png
Vid:
https://www.youtube.com/watch?v=gFij-Yymgvg

See what I mean? lol I give up.

**Comment by 13ace37** [comment]
`"SurfTimer" (272) by [z4lab] - Maintainer: Ace & totles`

https://www.youtube.com/watch?v=kF75R9RSD88

**Comment by 13ace37** [comment]
Are there any error logs?
I've updated the database at the 270 release.

**Comment by totles** [comment]
also whats your current SM/MM version? do a permission check on all csgo server files and look if you have our updated settings files (main.cfg, etc)

**Comment by 13ace37** [comment]
`ck_announcements` should have a `mode` and `group` column.
 
https://github.com/totles/z4lab-surftimer/blob/master/scripts/mysql-files/upgrading/upgrade-fluffy.sql#L15

**Comment by stunslave** [comment]
I have newest stable version of sourcemod and metamod. And yes I have all the necessary files from your latest release of  surftimer 272, and i have updated my db tables also. 

I'll try re-add the timer (as it without changing colours etc). Since it looks like it's broken on my side and not on urs and i'll see if that fixes it.

**Comment by totles** [comment]
you need to include the current colourvariables.inc and also if you have a self compiled version it might be hard to troubleshoot it

**Comment by stunslave** [comment]
Okay I tried ur compiled version. (version 272)
My compiled plugin is the same. (Both tested)

I did find something weird tho.

**After map reload:**

!ms shows 3500
!mv shows 10000
db shows 10000

Speed in-game when surfing doesn't go over 3500 (After map reload)

https://i.imgur.com/nZNL35V.png
https://i.imgur.com/e4RgKfG.png

**Comment by totles** [comment]
@stunslave the current master has this finally fixed, we also made a release for it (273) thanks for your help!
