### ISSUE TITLE
[BUG] ck_prestige_rank_vip

### ISSUE THREAD

**Issue by stunslave** [totles/z4lab-surftimer#72]
**I hate to be the bearer of bad news, but...**

In-game image kicked:
https://i.imgur.com/ygwxnAG.png
Surftimer Profile Image:
https://i.imgur.com/DEXOHKU.png
User in database image:
https://i.imgur.com/G35KhbV.png

Players that are VIP cannot connect to a prestige rank server.

**I set it to:** 

ck_prestige_all_styles "0" (tried with this on 1 also)
ck_prestige_rank "10"
ck_prestige_rank_vip "1"

Made my smurf a VIP (set to 3 in database) and tried to connect. (rank 45) The server kicked me.
Also got a friend to try connect in the images above.

Players that are rank 10 or better can connect, just VIP's can't connect.

**Comment by 13ace37** [comment]
That's not a bug.
Since https://github.com/totles/z4lab-surftimer/commit/114ce1a005703678d3f7eff4f4c029ebc5925ca8 we aren't using `ck_vipadmins` anymore. Our "VIP-System" works over `default_titles`.

**Comment by totles** [comment]
also afaik `ck_prestige_rank "10"` means he has to be rank 10 and higher, on the second screenshot you show his profile and he is rank 12 - as @13ace37 said tho this is the legacy VIP system which we will remove soon anyway

**Comment by 13ace37** [comment]
But he's VIP ^^ 
`ck_prestige_rank_vip "1"` overwrites the rank.

**Comment by stunslave** [comment]
Yes
ck_prestige_rank "10" and ck_prestige_rank_vip "1", which means he should be able to connect but cant. Even if he was rank 1000 he should still be able to connect. :P

Am i missing something here?

**Comment by stunslave** [comment]
> That's not a bug.
> Since [114ce1a](https://github.com/totles/z4lab-surftimer/commit/114ce1a005703678d3f7eff4f4c029ebc5925ca8) we aren't using `ck_vipadmins` anymore. Our "VIP-System" works over `default_titles`.

So will I need to add VIP members manually to default_titles.txt or will this be added to the db? Once you guys remove `ck_vipadmins` . And will there still be custom titles?

**Comment by 13ace37** [comment]
`ck_vipadmins` is still a thing. BUT we neither use custom titles or `ck_vipadmins` our VIPs are set manually through the `default_titles.txt`.

**Comment by stunslave** [comment]
ck_prestige_rank_vip "1" if i add the vip's to default_titles.txt will it work... or is this bugged?

EDIT:
**K IT WORKS, THANKS**

**Comment by stunslave** [comment]
When removing the Custom Titles, could you leave in sm_title (or rename sm_titlecolours) but for the colours of name and text, that way VIP players can still change their name and text colour when using default titles. :)

or just leave the whole menu in and change it so that Default Titles can be turned on and off through that menu (for VIP players that like to show off their rank title) as well as change name and text colours in it.

**I tend to get abit carried away thinking about this shit lol.**
