### ISSUE TITLE
[BUG] Prestige/VIP Server - Unranked players.

### ISSUE THREAD

**Issue by stunslave** [totles/z4lab-surftimer#74]
https://i.imgur.com/kaluC7z.png

**Unranked players** (players will 0 points) **can still connect to vip / prestige servers.**
 
In the image above "Gamerssassin cs.money" has no points. (**No results found for Gamerssassin cs.money** **in chat**) sm_profile check. Don't worry he got the **BANHAMMER**.

I did open a Bug report for this the other day, I don't know if anyone checked it. I may not have followed the guidelines of posting. lol - Hopefully this is my last bug report :D

**Comment by 13ace37** [comment]
So i took a look at your problem.

I've tried to join with my smurf and the following things happend:

![image](https://user-images.githubusercontent.com/29045525/63227040-7b7bee80-c1e2-11e9-8d00-ae602b3dd850.png)
![image](https://user-images.githubusercontent.com/29045525/63227044-8171cf80-c1e2-11e9-84d3-1e85df951821.png)
https://steamcommunity.com/id/xXxDxDxXx

**Comment by stunslave** [comment]
Well for some reason players that are not yet on the db keep joining the VIP server. 
Players that have never joined the servers previously (players that don't have a !profile yet). Once the player has a surftimer profile (After first connect) the player can no longer connect to the server.

I just gave sm_tempban to all my vip members on the vip server. When someone does connect without a profile they can just tempban them.
