### ISSUE TITLE
[Suggestion] Prestrafe Record

### ISSUE THREAD

**Issue by Marfimm** [totles/z4lab-surftimer#75]
~~**Prestrafe BOT Record**
It is good to record the prestrafe, because with it you can see if the player has bhop in the zone or any other glitch~~

**Prestrafe**
Record SR u/s to compare with PB u/s

![Screenshot_2](https://user-images.githubusercontent.com/17767263/63267569-c2acc280-c268-11e9-8201-5199a52624de.png)

**Comment by 13ace37** [comment]
I won't add any prestrafe recordings.
SR comparing maybe.

**Comment by totles** [comment]
I think he just means a text record for every stage of the SR, not a replay bot

**Comment by 13ace37** [comment]
I need to clean the database before adding new stuff to it.
