### ISSUE TITLE
[Suggestion] Latest/New Maps command

### ISSUE THREAD

**Issue by stunslave** [totles/z4lab-surftimer#76]
**I'll try describe this as best as I can!**

I would like to suggest adding a **sm_latestmaps (sm_newmaps)** menu command to show the newest maps added to the db/server. (this command may be better for the mapchooser) 

It would use `ck_maptier` table and show the latest 5 to 10 maps added to the db. These maps if possible can be selected from the **sm_newmaps Menu** to be nominated.

**Comment by 13ace37** [comment]
nominating out of it won't be added.
some people don't use a nomination mapchooser.
Also i don't really want to add new database stuff atm. Need to clean up the db stuff a little bit.
You could use this if you don't want to wait. https://github.com/maXusIprime/Surftimer/commit/d737fe1b540246e79ddccd03e5137603528c90f8

**Comment by stunslave** [comment]
I don't mind waiting it's chilled, although I may give that code test :>.. thanks
