### ISSUE TITLE
[BUG] (SQL) ck_checkpoints is not auto-generated on fresh install

### ISSUE THREAD

**Issue by TheGunter24** [totles/z4lab-surftimer#77]
**Describe the bug**
ck_checkpoints does not get auto-generated on fresh install

**Expected behavior**
fix :D

**Screenshots**
./.

**Additional context**
[SurfTimer.smx] [Surftimer] SQL Error (sql_selectRecordCheckpointsCallback): Table 'surftimerdev.ck_checkpoints' doesn't exist

**Comment by 13ace37** [comment]
I don't know where you get a code like this.
Are you sure you're using the newest version?

**Comment by TheGunter24** [comment]
"SurfTimer" (274) by [z4lab] - Maintainer: Ace & totles
should be the newest.

(suggestion)
maybe include a "start / blank" sql file (ive added one)
then include it in install instructions
maybe a version which includes premade zones / tiers
[SurfTimer.zip](https://github.com/totles/z4lab-surftimer/files/3530659/SurfTimer.zip)

**Comment by 13ace37** [comment]
![image](https://user-images.githubusercontent.com/29045525/63527993-6795fc80-c502-11e9-92bd-08614bf0c750.png)
![image](https://user-images.githubusercontent.com/29045525/63528067-8e543300-c502-11e9-8d92-cdd2596ce220.png)
Nothing changed since 2 years

**Comment by 13ace37** [comment]
> maybe a version which includes premade zones / tiers

no

> maybe include a "start / blank" sql file (ive added one)
then include it in install instructions

why?

**Comment by 13ace37** [comment]
May you check before writing `maybe a version which includes premade zones / tiers`
https://github.com/totles/z4lab-surftimer/blob/master/scripts/mysql-files/ck_zones.sql
https://github.com/totles/z4lab-surftimer/blob/master/scripts/mysql-files/ck_maptier.sql

**Comment by TheGunter24** [comment]
> > maybe a version which includes premade zones / tiers

> no
 
hm, was just something that i noticed, everything elso got created.
but it seems ok then, sry

> > maybe include a "start / blank" sql file (ive added one)
> > then include it in install instructions

> why?

so that no errors occour, due to missing db entries

> May you check before writing `maybe a version which includes premade zones / tiers`
> https://github.com/totles/z4lab-surftimer/blob/master/scripts/mysql-files/ck_zones.sql
> https://github.com/totles/z4lab-surftimer/blob/master/scripts/mysql-files/ck_maptier.sql

ye, i mean 2 dif. ver. of "surftimer.sql" one blank and one which includes zones/tier
may be easier for some ^^
