### ISSUE TITLE
[BUG] Database tables could not be created!

### ISSUE THREAD

**Issue by Cruze03** [totles/z4lab-surftimer#79]
[SM] Exception reported: [Surftimer] Database tables could not be created! Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(`steamid`)) DEFAULT CHARSET=utf8mb4' at line 1
[SM] Blaming: SurfTimer.smx
[SM] Call stack trace:
[SM]   [0] SetFailState
[SM]   [1] Line 118, surftimer/sql.sp::SQLTxn_CreateDatabaseFailed

Using [https://github.com/totles/z4lab-surftimer/releases/tag/274](url)this

https://cdn.discordapp.com/attachments/505779429067325444/614345723290583050/unknown.png

**Comment by 13ace37** [comment]
can't find `( steamid )) DEFAULT CHARSET=utf8mb4` in any of the sql relevant files and neither i would recommend using Ubuntu.

**Comment by Cruze03** [comment]
Ah alright man!
