### ISSUE TITLE
[BUG] Database tables could not be created

### ISSUE THREAD

**Issue by Cruze03** [totles/z4lab-surftimer#80]
[SM] Exception reported: [Surftimer] Database tables could not be created! Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near (steamid) DEFAULT CHARSET=utf8mb4' at line 1
[SM] Blaming: SurfTimer.smx
[SM] Call stack trace:
[SM]   [0] SetFailState
[SM]   [1] Line 118, surftimer/sql.sp::SQLTxn_CreateDatabaseFailed

MySQL Server Version: 5.7.27

**Comment by Cruze03** [comment]
Not duplicate though, previous one was `MariaDB` and this one is `MySQL`

**Comment by 13ace37** [comment]
when does it even occur?

**Comment by 13ace37** [comment]
and again you can search it up your self: `(steamid) DEFAULT CHARSET=utf8mb4` cannot be found in `queries.sp`

**Comment by 13ace37** [comment]
I can find ``(`steamid`)) DEFAULT CHARSET=utf8mb4`` as referred https://github.com/totles/z4lab-surftimer/issues/79#issue-484348654
May this one helps:
