### ISSUE TITLE
[Suggestion] cvar for replay bot trails

### ISSUE THREAD

**Issue by TheGunter24** [totles/z4lab-surftimer#82]
**Is your feature request related to a problem? Please describe.**
feature request

**Describe the solution you'd like**
add a ck_bot_trails 0/1

**Describe alternatives you've considered**
./.

**Additional context**
https://github.com/totles/z4lab-surftimer/commit/8e12fe63f4a4d851bf6a48a242ef8e8facd7854b
could do it manually, but might be useful for others

**Comment by TheGunter24** [comment]
+ 
(not sure) move player trail settings from clientpref to ck_playeroptions2 or / ck_trails

**Comment by 13ace37** [comment]
I've not added these templates for answers like 

> Is your feature request related to a problem? Please describe.
feature request

Neither is it a good idea to just write a comment below an issue.
That's the last warning after this I will instantly close all issues who don't follow the given template etc.

**Comment by 13ace37** [comment]
no answer after 1 week
