### ISSUE TITLE
BHOP/SURF Style Parkour [Suggestion]

### ISSUE THREAD

**Issue by sashajov** [totles/z4lab-surftimer#83]
Hello. I am using surf timer from cksurf. That is the best mode ever. I have one suggestion / idea. Can you tell me is it possible that you add Style Parkour like a in influx timer: https://github.com/InfluxTimer/sm-timer/blob/dev/addons/sourcemod/scripting/influx_style_parkour.sp

Lot of people using a surf timer for BHOP server also. Users like so much parkour mode. Thanks in advance.

**Comment by 13ace37** [comment]
It's called SurfTimer and thats not the right place to ask if you're not using our timer.

**Comment by sashajov** [comment]
Cksurf I was using few yrs ago, now I am using your timer for all servers. 3 surf and one bhop. Because of that I asked u. If it is not big job for you, you can add that style like a additional. That we can chose. Thanks.

**Comment by sashajov** [comment]
I guess that you didn't understand me because of my bad English.

**Comment by 13ace37** [comment]
This timer is used for surfing nothing else.
Neither do I add new styles to the timer.
