### ISSUE TITLE
Spaming console[BUG]

### ISSUE THREAD

**Issue by sashajov** [totles/z4lab-surftimer#84]
Hello dear. I have spam in console.

L 09/15/2019 - 12:52:38: [SM] Blaming: SurfTimer.smx
L 09/15/2019 - 12:52:38: [SM] Call stack trace:
L 09/15/2019 - 12:52:38: [SM]   [0] GetArrayArray
L 09/15/2019 - 12:52:38: [SM]   [1] Line 1100, surftimer/replay.sp::PlayReplay
L 09/15/2019 - 12:52:38: [SM]   [2] Line 1146, surftimer/hooks.sp::OnPlayerRunCmd
L 09/15/2019 - 12:52:38: [SM] Exception reported: Invalid index 6 (count: 6)
L 09/15/2019 - 12:52:38: [SM] Blaming: SurfTimer.smx
L 09/15/2019 - 12:52:38: [SM] Call stack trace:
L 09/15/2019 - 12:52:38: [SM]   [0] GetArrayArray
L 09/15/2019 - 12:52:38: [SM]   [1] Line 1100, surftimer/replay.sp::PlayReplay
L 09/15/2019 - 12:52:38: [SM]   [2] Line 1146, surftimer/hooks.sp::OnPlayerRunCmd
L 09/15/2019 - 12:52:39: [SM] Exception reported: Invalid index 6 (count: 6)

Spam starts few times daily. When start that spam, there is a SV and VAR 400+. Than I type !rm and all working good.

Do you have idea what that can be? Thanks.

**Comment by 13ace37** [comment]
May you follow our templates?

**Comment by sashajov** [comment]
Probably it is something with my dedicated server because I have no problem on another dedicated. Give me 1 day for checking and I will give you all information. Thanks.

**Comment by 13ace37** [comment]
> Give me 1 day for checking

No answer received!
