### ISSUE TITLE
Question more than a Issue but dont know where to ask

### ISSUE THREAD

**Issue by neroxqq** [totles/z4lab-surftimer#86]
Hello,

This is more of a question than issue, sorry i am new to github dont know where to post questions.
I need to know where to get this type of thing:

https://imgur.com/8qjxJPk (sorry for low quality lol)

**Comment by 13ace37** [comment]
> dont know where to post questions

You can't. Questions, please directly to me - either through [steam](https://steamcommunity.com/id/main_tryhard) or discord (Ace#5393)

> I need to know where to get this type of thing:

I bearly see something but I think that's a [KZTimer](https://github.com/klyve/KZTimerGlobal)
