### ISSUE TITLE
Jumpstartzone glitch.

### ISSUE THREAD

**Issue by eirik873** [totles/z4lab-surftimer#87]
I made it into a youtube video hopefully it speaks for it self :)

https://www.youtube.com/watch?v=EnArj1AhbL0&feature=youtu.be

i was a bit unclear. When u go of the startzone hold space until u hit the startzone again then release it. Now you are able to jump twice. i tested this on your server to incase i set something up wrong. if u need to contact me please do so on discord totles already knows who i am :)

**Comment by 13ace37** [comment]
Not following the given pattern/rules.
