### ISSUE TITLE
jumpglitch bug

### ISSUE THREAD

**Issue by eirik873** [totles/z4lab-surftimer#88]
**Describe the bug**
Being able to jump twice in the startzone.

**Expected behavior**
Not being able to jump twice in the startzone

**Screenshots**
https://www.youtube.com/watch?v=EnArj1AhbL0&feature=youtu.be

**Additional context**
This is kind of a problem since u can get out of the startzone with monster units. Especaly with shortstages/bonuses

**Comment by eirik873** [comment]
on further testing i have noticed jumping out of the zone then jumping back in not holding space wil allow u to prehop aswell

**Comment by eirik873** [comment]
so after a bit of reaserch we found something that can look promising from sourcemod - scripting - surftimer - hooks. There is from "page" 1385 - 1400+ something about jumping in the zone not sure if this wil help.

**Comment by 13ace37** [comment]
i guess you mean https://github.com/totles/z4lab-surftimer/blob/master/addons/sourcemod/scripting/surftimer/hooks.sp#L1385 ? am I right

**Comment by eirik873** [comment]
yeah i tried having my friend looking at it. and he also ended up at that line. the issue we found out is if we were to fix this what would happen to other stage zones that require bhopping.

**Comment by eirik873** [comment]
One solution could be that the zone resets u after x amouts of units out of the zone
