### ISSUE TITLE
[Suggestion] Fixing Backwards style.

### ISSUE THREAD

**Issue by eirik873** [totles/z4lab-surftimer#92]
**Is your feature request related to a problem? Please describe.**
A frustrating thing about going backwards is that its not only hard in its owne doing it but you also have to deal with if u where to be unlucky and hit ur back to a wall you wil be reverted to normal again. 

**Describe the solution you'd like**
I think this wil be very hard to solve but having a way where the time b4 u get reverted back to normal is pulled a bit so maybe you could have 3 secs incase u hit ur back to the wall. I know that there is a ton of ways to cheat a stage with a 3 sec delay  but as it is now it isnt 100% good.

As i said if possible put up a delay because there really isnt many people surfing backwards but those who do it kinda sucks doing alot of progress and then just getting reset because u missed the wall and u have to start over again. it unlocks a ton of maps

**Comment by 13ace37** [comment]
> As i said if possible put up a delay

There is a delay and by making the delay longer you can easily cheat. 
Neither do I see a reason to fix or change any of the styles expects of hsw.

**Comment by eirik873** [comment]
i respect that sorry to bother you :) have  a nice day


- Dank
