### ISSUE TITLE
[Suggestion] variable to en / disable "help" messages

### ISSUE THREAD

**Issue by TheGunter24** [totles/z4lab-surftimer#93]
**Is your feature request related to a problem? Please describe.**
it is not related to any problem. i just dont want users to be forced to switch between hundrets of commands to find what they need. this is listed elsewhere, so this message is not needed.

**Describe the solution you'd like**
a convar to en / disable the help message

**Describe alternatives you've considered**
edit the "phrases"/"translations" for surtimer

**Additional context**
i mean the chat messages saying "type !help to get a list of surf commands..."

**Comment by 13ace37** [comment]
i dont see a reason to add this.
