### ISSUE TITLE
[BUG] HUD is not formatted

### ISSUE THREAD

**Issue by TheGunter24** [totles/z4lab-surftimer#95]
**Describe the bug**
the speed / rank hud is bugged, it is not formatting

**Expected behavior**
update hud or rewrite

**Screenshots**
https://abload.de/img/20191119172900_1jlkuz.jpg

**Additional context**
could maybe be a include, but any other color in chat works

**Comment by 13ace37** [comment]
I think valve just fucked the whole timer

**Comment by TheGunter24** [comment]
well nice 
:)
is it also not possible to only have white text in hud ?

**Comment by 13ace37** [comment]
would be possible but also that would look bad af

**Comment by TheGunter24** [comment]
for now that would be a fix, sure someone will find a way to color it again later 👍

**Comment by 13ace37** [comment]
currently, it's kinda hard to change something on the timer since I'm nearly ready to publish 1.8 and now the update fucked it up.

**Comment by TheGunter24** [comment]
fuck :/ youll get this, i believe in you ^^

**Comment by sashajov** [comment]
@TheGunter24 I made changes for a timer to be white, without bugs.

misc.sp https://pastebin.com/34jFJWhn

Compiled whole plugin: https://www.sendspace.com/file/fv3blb

All you need to do is to compile this misc.sp with all other .sp files.

It's only a temporary solution, but I am sure the z4lab team will do it right.

**Comment by sashajov** [comment]
@13ace37 Bro, there is a hotfix. ( https://forums.alliedmods.net/showthread.php?p=2673590#post2673590 ) I tested, it's working but speed is missing. https://i.imgur.com/LUG9Uzi.png 
Do you have some idea?

**Comment by 13ace37** [comment]
Sorry but i won't use anything related to Franc1sco.

**Comment by sashajov** [comment]
ok

**Comment by 13ace37** [comment]
not completely fixed but it has color again. 

https://github.com/totles/z4lab-surftimer/commit/85d520590e8615115efe15e4de416ff37ad58f86

**Comment by 13ace37** [comment]
https://github.com/totles/z4lab-surftimer/releases/tag/280pre
