### ISSUE TITLE
[Question] [Suggestion] Removing One Jump Limit and Prespeed on the Stages

### ISSUE THREAD

**Issue by sashajov** [totles/z4lab-surftimer#99]
**Please don't rush with answering on my question, I know that you have a lot of things to fix after these latest "VOLVO" updates and that you working on your new 1.8v**

**Is your feature request related to a problem? Please describe.**
I know that there is an option for disable/enable One Jump Limit for all zones with the command (ck_one_jump_limit "1/0") in surftimer.cfg, but I didn't find any command for doing that only for stages.

**Describe the solution you'd like**
I know, there is an option in !zones menu for removing one jump limit and max prespeed for each zone manually, but is it possible to separate one jump limit command from all zones to start/end and stages?

e.g.

// Enables/Disables the one jump limit globally for the start zone
// -
// Default: "1"
ck_one_jump_limit_start_zone "1"

// Enables/Disables the one jump limit globally for all stages
// -
// Default: "0"
ck_one_jump_limit_stages "0"

and probably

// Limit prespeed settings globally for start zone
// -
// Default: "250"
// Minimum: "200"
// Maximum: "3500"
ck_prespeed_limit_start_end "250"

// Limit prespeed settings globally for all stages
// -
// Default: "250"
// Minimum: "200"
// Maximum: "3500"
ck_prespeed_limit_start_end "250"

Or something like a that. :)

I hope that is not a so hard job for you, but if it is, we will continue to do it manually for each zone.

Probably there is exist some king a solution that I didn't find. :D 

Greetings.

**Comment by 13ace37** [comment]
There is no command but you can remove it by using the database.

**Comment by sashajov** [comment]
Huh, nice idea. Please tell me, in column "zonetype" 1 is start zone, 2 is end zone, 3 is stage and 4 is cps? Am I right?

**Comment by 13ace37** [comment]
```
Zonetype
1 = Start
2 = End
3 = Stage
4 = Checkpoint
5... = Util Zones (NoJump etc.)

ZonetypeID
0 = Map
1 = Bonus
```

Replace all OneJumpLimits: 

```SQL
-- Map
UPDATE `surftimer`.`ck_zones` SET `onejumplimit` = '0' WHERE `zonetype` = '0' AND `zonetypeid` = '0';
-- Bonus
UPDATE `surftimer`.`ck_zones` SET `onejumplimit` = '0' WHERE `zonetype` = '0' AND `zonetypeid` = '1';
-- Stages
UPDATE `surftimer`.`ck_zones` SET `onejumplimit` = '0' WHERE `zonetype` = '1' AND `zonetypeid` = '0';
```

Set all prespeeds:
_replace `xxx` with the wanted prespeed_

```SQL
-- Map Start
UPDATE `surftimer`.`ck_zones` SET `prespeed` = 'xxx' WHERE `zonetype` = '0' AND `zonetypeid` = '0';
-- Bonus Start
UPDATE `surftimer`.`ck_zones` SET `prespeed` = 'xxx' WHERE `zonetype` = '0' AND `zonetypeid` = '1';
-- Stages
UPDATE `surftimer`.`ck_zones` SET `prespeed` = 'xxx' WHERE `zonetype` = '1' AND `zonetypeid` = '0';
```

You can also add `AND mapname = 'surf_xxxx'` at the end to replace it only on one map
